FROM openjdk:17-jdk-slim

MAINTAINER ashwin.com

COPY target/accounts-0.0.1-SNAPSHOT.jar accounts-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","accounts-0.0.1-SNAPSHOT.jar"]

#docker run -p 8080:8080 ashwinkumar05/accounts:s4
